server:
  port: 10010
spring:
  application:
    name: leyou-gateway
zuul:
  prefix: /api
  routes:
    item-service: /item/**
    item-upload: /upload/**
    search-service: /search/**
  ignored-services:    #设置服务路由的忽略
    - item-service
    - item-upload
    - search-service
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

ly:
  cors:
    allowedOrigins:
      - http://manage.leyou.com
      - http://www.leyou.com
    allowCredentials: true
    allowedHeaders:
      - "*"
    allowedMethods:
      - GET
      - POST
      - DELETE
      - PUT
      - OPTIONS
      - HEAD
    maxAge: 3600
    filterPath: "/**"
