server:
  port: 10010
spring:
  application:
    name: leyou-gateway
zuul:
  prefix: /api
  routes:
    item-service: /item/**
  ignored-services:    #设置服务路由的忽略
    - item-service
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
