server:
  port: 8083
spring:
  application:
    name: search-service
  data:
    elasticsearch:
      cluster-name: elasticsearch         #配置elasticsearch的名字
      cluster-nodes: 192.168.2.128:9300                     #配置端口号的地址

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka  #配置注册中心地址
  instance:                               #作为客服端应该配置实列
    lease-renewal-interval-in-seconds: 5    #心跳时间（续约时间）
    lease-expiration-duration-in-seconds: 15  #服务拉取时间
    ip-address: 127.0.0.1
    prefer-ip-address: true   #优先使用ip地址


