server:
  port: 8081

spring:
  application:  #服务名
    name: item-service
  datasource:   #数据库连接池数据
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/heima88?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: hmj050117
    hikari:
      max-lifetime: 28830000 # 一个连接的生命时长（毫秒）
      maximum-pool-size: 9 # 连接池中允许的最大连接数。
logging:  #日志
  level:
    cn.leyou: debug
eureka:   #eurekake客户端
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    register-with-eureka: true #false为不注册自己
    fetch-registry: false   #false为不拉取服务
  instance:
    lease-renewal-interval-in-seconds: 5 # 5秒钟发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期


